### ISSUE TITLE
Check if code is still needed after rig cleanup

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#210]
These methods where used in rig version but data was never actually used.
Are they needed elsewhere?

AbstractOutgoingEdgePartition.traffic_weight()

**Comment by alan-stokes** [comment]
nope, but before i give you the swingy mallet. It was proposed that a rouer could route better knowing the number of protential neurons that fire through that mc edge. We dont use it yet, but maybe next week will view it as needed. That said, id just go via the graph to get that data instead of storing it in the outgoing partition....... guess if you have a SSP which fires more than once per timestep, its weight is higher than its neuron count..... so maybe worth keeping it in?????

**Comment by Christian-B** [comment]
I see  @alan-stokes's point.

While I don't expect we will ever use this value it is better to keep it around.
