### ISSUE TITLE
AbstractSlicesConnect.could_connect lost in reduce overhead

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/PACMAN#434]
Not sure how useful if ever was so ok to close with a yep not worth the effort to keep.

Not a blocked for reduce_overhead PR

When we had MachineEdges we had some that where AbstractSlicesConnect which could then say which Machinevertices where KNOWN never to connect.

Use cases include
DelayAfferentApplicationEdge (Which is sort of a OneToOneConnector)
Edges based on
FromListConnector
OneToOneConnector

**Comment by rowleya** [comment]
The removal as it stands is intentional; by having the same edges coming into every machine vertex, you can reduce the work required and re-use much of the data between the vertices.  

That said, it could potentially be useful to bring something like this back at some point, which might end up doing something like removing some of the actual targets when routing.

**Comment by Christian-B** [comment]
if it is every needed reopen this issue or create a new one.
