### ISSUE TITLE
Make the graph a single object which contains both Application and Machine vertices and edges

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#54]
The separation between graphs shouldn't be necessary.  Partitioning should be able to work on a "Graph" which then only partitions Application vertices.  An ApplicationEdge would be any edge which starts or ends on an ApplicationVertex, but the other vertex of the edge can be either another ApplicationVertex or a MachineVertex.  During partitioning, an ApplictionVertex is turned into one or more MachineVertices an ApplicationEdge is turned into one or more MachineEdges as is currently done.  The only difference is that if an ApplicationEdge starts on a MachineEdge, all MachineEdges of the ApplicationEdge start on that same MachineEdge, and similarly if the ApplicationEdge ends on a MachineEdge.  Partitioning should also simply copy any MachineEdge or MachineVertex from the Application graph to the Machine graph.

Graph Mapping is still a useful concept, since there will still be a graph before Partitioning and a graph after Partitioning.  The GraphMapper should then only contain mappings between ApplicationVertices and MachineVertices and ApplicationEdges and MachineEdges, which would mean it would be empty if there are no ApplicationVertices in the original graph.

**Comment by alan-stokes** [comment]
hi rowley, 

i dont get this bit.

The only difference is that if an ApplicationEdge starts on a MachineEdge, all MachineEdges of the ApplicationEdge start on that same MachineEdge, and similarly if the ApplicationEdge ends on a MachineEdge

Im sure some of those are meant to be verts, but not sure which ones now.

Im not sure what gains you get from this refactor. for every application vertex, we already have a machine vertex equiv, and they have been designed to work with separately. 

1. If you place them all in the same graph, you'll make edge pruning etc rather difficult. you'd need to remove the immutability of the graph to sort this out.
2. Having them separate also allows you operate at whichever scope you wish without having to worry about searching though other stuff (small argument). 
3. we'd need to revisit the workflow and every algorithm, because now your going to have different calls for the different vert types. Wed basically be reverting most of the last massive refactor.

unless there's a valid use case for this, i'm inclined to say the gains do nort outweigh the workload and the relearning of all the structure yet again.

**Comment by rowleya** [comment]
The advantage is that you can leave MachineVertices as MachineVertices i.e. you don't have to make an ApplicationVertex that you know won't be split up and then also have a MachineVertex.  Thus you can then just have a MachineVertex.  Users also then don't need to choose which graph to add things to - they just add them to the graph.  To address your point:

1. Edge pruning would be the same after this change, and in fact better, since you can now choose to prune either type of edge.  The immutability argument does not stand here, as we already create a new copy of the graph - nothing would change.

2. This is true to some extent, but we could still have a concept of an ApplicationGraph vs MachineGraph in PACMAN XML without the need for this to translate to actual different classes.  The ApplicationGraph is the graph that might have application vertices in it (though it might not) and the MachineGraph is the graph that only contains machine vertices.

3. See 2.  No refactor needed.

This is basically a way of allowing a MachineVertex in an ApplicationGraph.  It would be acceptable to keep the Graph objects separate if preferred with the ApplicationGraph allowing all vertex types and the MachineGraph only allowing machine vertices and edges as it currently is.  Thus it is hardly a refactor at all - just a minor change to partitioning.

**Comment by alan-stokes** [comment]
to bounce back.
1. drrr your right *head slam* (obviously need more tea here)
2. if you have the concept of ApplicationGraph vs MachineGraph, then putting them in the same object just makes management more work (in my view). and this would result in a back peddle of explicitness.
3. if they are the same graph in the end, then to get the list of app verts, it would need something like get-application_verts() and get_machine_verts(). this is basically a back peddle on our refactor of 2 graphs with the same interface of get_verts(). if its 2 graphs, then i dont see the logic in the rewrite, as you'll have to do searches to find your verts etc. which will slow the system down

I think we'd nee dto sit down with a doodle, because right now im not seeing what your seeing, and id like to put machine verts into a app vertex application, but just dumping them into the graph and expecting everything to work......... i just cant see it.

**Comment by rowleya** [comment]
OK, so the suggestion has become:

1. The ApplicationGraph and MachineGraph are still kept separate
1. The ApplicationGraph accepts MachineVertex and MachineEdge into it
1. An ApplicationEdge can have a MachineVertex as pre or post vertex (or both? - if so, need to replace with a MachineEdge in the partitioner but this should work).

At partitioning:

1. Partition ApplicationVertex into multiple MachineVertex instances and add to a MachineGraph
1. Copy MachineVertex instances into MachineGraph
1. Copy MachineEdge instances into MachineGraph
1. Convert ApplicationEdge instances to MachineEdge instances; if an edge starts on a MachineVertex, a MachineEdge is created from the MachineVertex to every MachineVertex of the post_vertex (which might also be a MachineVertex); if an edge ends on a MachineVertex, a MachineEdge is created to the MachineVertex from every MachineVertex of the pre_vertex.

Additionally, any ApplicationVertex that currently uses the graph for memory calculations (see sPyNNaker AbstractPopulationVertex in particular) will have to take account that the pre- or post-vertex of an edge might be a MachineVertex rather than an ApplicationVertex.  This should help with the memory calculations though, since you don't know how many MachineVertices an ApplicationVertex will end up as, but you know a MachineVertex will stay the same.

**Comment by alan-stokes** [comment]
rubber stamped.

**Comment by AlexRast** [comment]
I'm inclined to agree with Alan on this one. It seems better and less confusing 
long-term to keep ApplicationVertices and MachineVertices separate and 
applicable only to their Graph. Now, the Graphs, Vertices and Edges could 
inherit from largely identical (non-abstract) classes implementing the same, but 
retain their separate identity for the purposes of internal representation.

Another reason to have a separate ApplicationGraph and MachineGraph is that then 
you can directly inspect the differences between the high-level netlist the 
application needs and how that actually maps to the hardware. This could be 
especially useful when experimenting with different mapping algorithms.

**Comment by dkfellows** [comment]
With the advent of splitters, we now solve this (or at least _can_ solve this) by wrapping machine vertices with trivial application vertices (with `AbstractOneAppOneMachineVertex` having most of the machinery pre-built).
