### ISSUE TITLE
Support dynamically allocated port numbers for ReverseIPTag

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/PACMAN#55]
The ReverseIPTag specifies a port number - it could be useful to not require this and have one dynamically allocated if not specified.

**Comment by AlexRast** [comment]
Would this not require the device sending information via a ReverseIPTag to be 
notified of what port it had been allocated? Assuming this is the case there 
will need to be some sort of protocol for informing the device at run-time - and 
presumably before the simulation starts. In general, the system would:

1) allocate the port
2) Transmit a message to the device indicating what port it should use (and 
presumably the device is identified by IP address?
3) wait for receipt of an acknowledgement from the device that it has received 
the port allocation and configured itself appropriately
4) continue.

**Comment by alan-stokes** [comment]
hi alex, I'm about to start doing this (requested from basab, for multiple runs of different scripts at the same time). The view point myself and rowley had when we made the issue was that instead of creating a ip or reverse ip tag constraint with a port (when constraints are needed) or where we build a connection with a given port (buffering interfaces), we'd instead open a connection and ask for what port it selected, and use that instead. We'd also send that data as config with the system region (as buffering stuff resides in the recording interface, which i think is still governed by the system region in dsg) for the c code to configure. The same can be done with the RIPMCS (as its using the sdp ports covered in the fec.constants.py on lines 53 to 66). 

on discussing with a external device (aka a visualizer, for the live output connection port), that is what the database notification protocol is used for. Id expect the external device during the reading of the database to find out what port was allocated to the vertices it wanted to read from and work accordingly. There is a tag and reverse iptag table in there. 

there is some issue for the overarching notification protocol, as the protocol takes a port for communicating where the database is, and for acknowledging its finished reading the database, and we'll need to ensure that they are configured automatically, correctly. That one we've not been able to think of a great solution to at moment (see #71 for our idea), if you have any better ideas, please feel free to expose them. 

oh and a wrap up, I'll be doing this issue in conjunction with issue #71 and #70 in fec.

alan

**Comment by alan-stokes** [comment]
done
